package love.chihuyu.game

enum class StatisticsType {
    // Runner
    HUNTERS_KILLED,
    // Hunter
    RUNNERS_KILLED,
    DEATHES,
    // Global
    PLAYED,
    VICTORIED,
    ALIVE_TIME,
    TIME_TO_THE_END,
    TIME_TO_NETHER,
    MOBS_KILLED,
    ENDERMANS_KILLED,
    BLAZES_KILLED,
    BLOCKS_BROKEN,
    BLOCKS_PLACED,
    TRAVELED,
    ITEMS_TRADED,
    ITEMS_BARTERED,
    OPENED_LOOTS,
    FOODS_CRAFTED,
    IRONS_SMELT,
    COALS_MINED,
    POTIONS_BREWED,
    ITEMS_CRAFTED,
    ITEMS_ENCHANTED,
    TOOLS_REPAIRED,
    ARROW_SHOOTED,
    ARROW_HITTED
}
